title: QUIX Docs
description: >- # this means to ignore newlines until "baseurl:"
  QUIX 1.0 documentation
source: docs
baseurl: "/quixcc" # the subpath of your site, e.g. /blog
url: "https://kracken256.github.io/quixcc/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
