name: qpkg
base: core22
version: '0.0.0'
summary: QUIX Package and Build System
description: |
  QPKG is a comprehensive tool to install, create, compile, analyze, recompose, and
  distribute software packages using the QUIX Programming language. It integrates
  the entire QUIX Toolchain and provides a consistent and reliable way to deal with
  QUIX projects.

confinement: devmode

parts:
  qpkg:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DSTRIP_OUTPUT=ON -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
    source: .
    build-packages:
      - libssl-dev
      - libboost-all-dev
      - libzstd-dev
      - libclang-common-14-dev
      - rapidjson-dev
      - libdeflate-dev
      - libreadline-dev
      - libclang-dev
      - libclang-cpp-dev
      - nlohmann-json3-dev
      - libgoogle-glog-dev
      - cmake
      - make
      - clang
      - llvm-14-dev
      - upx
      - gnupg2
      - dpkg-dev
    stage-packages:
      - git
      - libdeflate0
      - libllvm14
      - libclang-cpp14
    override-stage: |
      snapcraftctl stage
      rm /usr/lib/x86_64-linux-gnu/libicuio.so.70.1 /usr/lib/x86_64-linux-gnu/libicutest.so.70.1

apps:
  qpkg:
    command: usr/bin/qpkg
