name: qpkg
base: core22
version: '0.0.0'
summary: QUIX Package and Build System
description: |
  QPKG is a comprehensive tool to install, create, compile, analyze, recompose, and
  distribute software packages using the QUIX Programming language. It integrates
  the entire QUIX Toolchain and provides a consistent and reliable way to deal with
  QUIX projects.

confinement: devmode

parts:
  qpkg:
    plugin: autotools
    autotools-configure-parameters: ["--prefix=/usr"]
    source: https://github.com/Kracken256/quix.git
    build-packages: []
apps:
  qpkg:
    command: usr/bin/qpkg