name: qpkg
base: core22
version: '0.0.0'
summary: Nitrate Package and Build System
description: |
  QPKG is a comprehensive tool to install, create, compile, analyze, recompose, and
  distribute software packages using the Nitrate Programming language. It integrates
  the entire Nitrate Toolchain and provides a consistent and reliable way to deal with
  Nitrate projects.

confinement: classic

parts:
  qpkg:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DSTRIP_OUTPUT=ON -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_C_COMPILER=/usr/bin/clang
    source: .
    build-packages:
      - libssl-dev
      - libboost-all-dev
      - libzstd-dev
      - libclang-common-14-dev
      - rapidjson-dev
      - libdeflate-dev
      - libreadline-dev
      - nlohmann-json3-dev
      - libgoogle-glog-dev
      - clang
      - llvm-14-dev
    build-attributes:
     - enable-patchelf
    stage-packages:
      - git
      - libdeflate0
    override-stage: |
        snapcraftctl stage
        rm $SNAPCRAFT_PART_INSTALL/usr/lib/libnitrate.a
        rm $SNAPCRAFT_PART_INSTALL/usr/lib/libnitrate-core.a
        rm $SNAPCRAFT_PART_INSTALL/usr/lib/libnitrate-lexer.a
        rm $SNAPCRAFT_PART_INSTALL/usr/lib/libnitrate-seq.a
        rm $SNAPCRAFT_PART_INSTALL/usr/lib/libnitrate-parser.a
        rm $SNAPCRAFT_PART_INSTALL/usr/lib/libnitrate-ir.a
        rm $SNAPCRAFT_PART_INSTALL/usr/lib/libnitrate-emit.a
        rm -rf $SNAPCRAFT_PART_INSTALL/usr/include

apps:
  qpkg:
    command: usr/bin/no3
