name: qpkg
base: core22
version: '0.0.0'
summary: QUIX Package and Build System
description: |
  QPKG is a comprehensive tool to install, create, compile, analyze, recompose, and
  distribute software packages using the QUIX Programming language. It integrates
  the entire QUIX Toolchain and provides a consistent and reliable way to deal with
  QUIX projects.

confinement: devmode

parts:
  qpkg:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DSTRIP_OUTPUT=ON
    source: .
    build-packages: 
      - libboost-all-dev
      - libdeflate-dev
      - libyaml-cpp-dev
      - libhpdf-dev
      - libssl-dev
    stage-packages:
      - git
      
apps:
  qpkg:
    command: usr/bin/qpkg
