name: nitrate
base: core24
version: '0.0.0'
summary: Nitrate Package and Build System
description: |
  Nitrate is a comprehensive tool to install, create, compile, analyze, recompose, and
  distribute software packages using the Nitrate Programming language. It integrates
  the entire Nitrate Toolchain and provides a consistent and reliable way to deal with
  Nitrate projects.

confinement: strict

parts:
  nitrate:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=OFF -DSTRIP_OUTPUT=ON -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_C_COMPILER=/usr/bin/clang
    source: .
    build-packages:
     - libboost-all-dev
     - libssl-dev
     - libgoogle-glog-dev
     - libyaml-cpp-dev
     - rapidjson-dev
     - nlohmann-json3-dev
     - libreadline-dev
     - libzstd-dev
     - llvm-18-dev
     - libpolly-18-dev
     - clang
    build-attributes:
     - enable-patchelf
    stage-packages:
      - git
      - libunwind8
    override-stage: |
        snapcraftctl stage
        rm -rf $SNAPCRAFT_PART_INSTALL/usr/include
        rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libunwind-coredump.so.0.0.0
        rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libunwind-ptrace.so.0.0.0
        rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu/libunwind-x86_64.so.8.0.1

apps:
  nitrate:
    command: usr/bin/no3
    plugs: 
      # Allow access to the network for fetching packages and LSP TCP server
      - network
      - network-bind
      # Files and directories access
      - home
      - removable-media