name: Verify Snapcraft

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Dump OS information
      run: |
        echo "OS: ${{ runner.os }}"
        echo "OS Version: ${{ runner.os_version }}"
        echo "Architecture: ${{ runner.arch }}"
        cat /etc/os-release
      shell: bash

    - name: Install dependencies
      run: |
        sudo apt install -y snapd
      shell: bash

    - name: Install Snapcraft
      run: |
        sudo snap install snapcraft --classic
      shell: bash

    - name: Verify Snapcraft
      run: |
        snapcraft --version
      shell: bash

    - name: Build Snap
      run: |
        sudo lxd init --auto
        sudo snapcraft -v
      shell: bash